general_params:
  train_year: &train_year 2020
  test_year: &test_year 2021
  patch_size: &patch_size 128
  prefixs: &prefixs
    opt: opt
    sar: sar
    previous: previous
    label: label
    prediction: pred
    cloud: cloud
  experiments_cfg_path: &experiments_cfg_path experiments
  experiments_paths: &experiments_path
    folder: D:\Ferrari\Projects\thesis\experiments
    models: models
    logs: logs
    predicted: predicted
    visual: visual
    results: results
  opt_bands: &opt_bands 13 #number of bands per optical image
  sar_bands: &sar_bands 2 #number of bands per SAR image
  #n_opt_images: &n_opt_images 2 #!5 #number of optical images
  #n_sar_images: &n_sar_images 12 #number of optical images
  n_classes: &n_classes 3 #number of classes
  n_models: &n_models 5 #number of models to be trained for each experiment
  resunet_depths: &resunet_depths [32, 64, 128, 256]
original_data:
  opt:
    n_bands: *opt_bands 
    folder: D:\Ferrari\Projects\thesis\data\opt_full_L1C #!check the number of optical bands
    imgs:
      train:
        - 2019-08-06-2019-08-07.tif
        - 2019-11-24-2019-11-25.tif
        - 2020-02-17-2020-02-18.tif
        - 2020-05-02-2020-05-03.tif
        - 2020-07-31-2020-08-01.tif
      test:
        - 2020-07-31-2020-08-01.tif
        - 2020-11-03-2020-11-04.tif
        - 2021-02-01-2021-02-02.tif
        - 2021-05-27-2021-05-28.tif
        - 2021-07-16-2021-07-17.tif
  sar:
    n_bands: *sar_bands 
    folder: D:\Ferrari\Projects\thesis\data\sar
    imgs:
      train: 
        - 2019-07-14-2019-08-14.tif
        - 2019-08-15-2019-09-15.tif
        - 2019-09-16-2019-10-17.tif
        - 2019-10-18-2019-11-18.tif
        - 2019-11-19-2019-12-20.tif
        - 2019-12-21-2020-01-21.tif
        - 2020-01-22-2020-02-22.tif
        - 2020-02-23-2020-03-25.tif
        - 2020-03-26-2020-04-26.tif
        - 2020-04-27-2020-05-28.tif
        - 2020-05-29-2020-06-29.tif
        - 2020-06-30-2020-07-30.tif
      test: 
        - 2020-06-30-2020-07-30.tif
        - 2020-07-31-2020-08-30.tif
        - 2020-08-31-2020-09-30.tif
        - 2020-10-01-2020-10-31.tif
        - 2020-11-01-2020-12-01.tif
        - 2020-12-02-2021-01-01.tif
        - 2021-01-02-2021-02-01.tif
        - 2021-02-02-2021-03-03.tif
        - 2021-03-04-2021-04-02.tif
        - 2021-04-03-2021-05-02.tif
        - 2021-05-03-2021-06-01.tif
        - 2021-06-02-2021-07-01.tif
  prodes:
    folder: D:\Ferrari\Projects\thesis\prodes
    defor_2007: accumulated_deforestation_2007.shp
    hydrography: hydrography.shp
    no_forest: no_forest.shp
    residual: residual.shp
    yearly_deforestation: yearly_deforestation.shp
tiles_params:
  lines: 3
  columns: 3
  train_tiles: [0, 1, 3, 5, 8]
  path: D:\Ferrari\Projects\thesis\data\general\tiles.tif
label_params:
  def_inner_buffer: 3
  def_outer_buffer: 3
  train_year: *train_year
  test_year: *test_year
  train_path: D:\Ferrari\Projects\thesis\data\general\label_train.tif
  test_path: D:\Ferrari\Projects\thesis\data\general\label_test.tif
previous_def_params:
  train_path: D:\Ferrari\Projects\thesis\data\general\previous_train.tif
  test_path: D:\Ferrari\Projects\thesis\data\general\previous_test.tif
  train_year: *train_year
  test_year: *test_year
preparation_params:
  folder: C:\Users\felferrari\Documents\projetos\thesis\prepared #D:\Ferrari\Projects\thesis\prepared_data
  train_folder: train
  #train_data: train.csv
  validation_folder: validation
  #validation_data: validation.csv
  test_folder: test
  prepared_data: prepared.yaml
  patch_size: *patch_size
  opt_bands: *opt_bands 
  sar_bands: *sar_bands 
  patch_overlap: 0.7
  min_def_proportion: 0.02
  prefixs: *prefixs
training_params:
  n_models: *n_models
  experiments_cfg_path: *experiments_cfg_path
  experiments_paths: *experiments_path
  patch_size: *patch_size
  batch_size: 32
  opt_bands: *opt_bands 
  sar_bands: *sar_bands 
  loss_fn: 
    module: torch.nn.CrossEntropyLoss
    ignore_index: 2
    weights: [0.2, 0.8, 0]
  optimizer:
    module: torch.optim.Adam
    params:
      lr: 2.0e-5
  early_stop:
    patience: 10
    min_delta: 1.0e-5
    min_epochs: 0
  max_epochs: 500
  n_classes: *n_classes
prediction_params:
  experiments_paths: *experiments_path
  patch_size: *patch_size
  n_classes: *n_classes
  prefixs: *prefixs
  n_models: *n_models
  batch_size: 32
  prediction_remove_border: 8
  prediction_overlaps: [0.2, 0.3]
  opt_bands: *opt_bands 
  sar_bands: *sar_bands 
  #n_opt_images: *n_opt_images 
  #n_sar_images: *n_sar_images

experiments:
  exp_X:
    model: models.resunet.networks.ResUnetOpt # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 1 ,2 ,3 ,4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 1, 2, 3, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_46:
    model: models.simplyresunet.networks.ResUnetOpt # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_47:
    model: models.simplyresunet.networks.ResUnetSAR # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_48:
    model: models.simplyresunet.networks.ResUnetEF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_49:
    model: models.simplyresunet.networks.ResUnetJF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_50:
    model: models.simplyresunet.networks.ResUnetLF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: *resunet_depths

  exp_51:
    model: models.simplyresunet.networks.ResUnetOpt # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: [64, 128, 256, 512]

  exp_52:
    model: models.simplyresunet.networks.ResUnetSAR # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: [64, 128, 256, 512]

  exp_53:
    model: models.simplyresunet.networks.ResUnetEF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: [64, 128, 256, 512]

  exp_54:
    model: models.simplyresunet.networks.ResUnetJF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: [64, 128, 256, 512]

  exp_55:
    model: models.simplyresunet.networks.ResUnetLF # ResUnetOpt ResUnetSAR ResUnetEF ResUnetJF ResUnetLF
    prefixs: *prefixs
    opt_bands: *opt_bands
    sar_bands: *sar_bands
    n_classes: *n_classes
    train_opt_imgs: 
      - [0, 4]
    train_sar_imgs: 
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    test_opt_imgs: 
      - [0, 4]
    test_sar_imgs:
      - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    resunet_depths: [64, 128, 256, 512]