general_params:
  train_year: &train_year 2019
  test_year: &test_year 2020
  patch_size: &patch_size 128
  data_prefix: &data_prefix data
  label_prefix: &label_prefix label
  prediction_prefix: &prediction_prefix pred
  experiments_cfg_path: &experiments_cfg_path experiments
  experiments_paths: &experiments_path
    folder: D:\Ferrari\Projects\thesis\experiments
    models: models
    logs: logs
    predicted: predicted
    visual: visual
    results: results
  opt_bands: &opt_bands 13 #number of bands per optical image
  sar_bands: &sar_bands 2 #number of bands per SAR image
  n_opt_images: &n_opt_images 2 #5 #number of optical images
  n_sar_images: &n_sar_images 2 #12 #number of optical images
  n_classes: &n_classes 3 #number of classes
  n_models: &n_models 5 #number of models to be trained for each experiment
  resunet_depths: &resunet_depths [32, 64, 128, 256]
original_data:
  opt:
    n_bands: *opt_bands 
    folder: D:\Ferrari\Projects\thesis\data\opt
    imgs:
      train:
        -
          - 18193.tif
          - 19208.tif
      test:
        -
          - 19208.tif
          - 20213.tif
  sar:
    n_bands: *sar_bands 
    folder: D:\Ferrari\Projects\thesis\data\sar
    imgs:
      train: 
        -
          - 18198.tif
          - 19217.tif
      test: 
        -
          - 19217.tif
          - 20212.tif
  prodes:
    folder: D:\Ferrari\Projects\thesis\prodes
    defor_2007: accumulated_deforestation_2007.shp
    hydrography: hydrography.shp
    no_forest: no_forest.shp
    residual: residual.shp
    yearly_deforestation: yearly_deforestation.shp
tiles_params:
  lines: 3
  columns: 3
  train_tiles: [0, 1, 3, 5, 8]
  path: D:\Ferrari\Projects\thesis\data\general\tiles.tif
label_params:
  def_inner_buffer: 3
  def_outer_buffer: 3
  train_year: *train_year
  test_year: *test_year
  train_path: D:\Ferrari\Projects\thesis\data\general\label_train.tif
  test_path: D:\Ferrari\Projects\thesis\data\general\label_test.tif
previous_def_params:
  train_path: D:\Ferrari\Projects\thesis\data\general\previous_train.tif
  test_path: D:\Ferrari\Projects\thesis\data\general\previous_test.tif
  train_year: *train_year
  test_year: *test_year
preparation_params:
  folder: D:\Ferrari\Projects\thesis\prepared_data
  train_folder: train
  train_data: train.csv
  validation_folder: validation
  validation_data: validation.csv
  test_folder: test
  test_data: test.csv
  prediction_folder: prediction
  prediction_data: prediction_data
  statistics_file: stats.json
  patch_size: *patch_size
  patch_overlap: 0.7
  min_def_proportion: 0.02
  data_prefix: *data_prefix
  label_prefix: *label_prefix 
training_params:
  n_models: *n_models
  experiments_cfg_path: *experiments_cfg_path
  experiments_paths: *experiments_path
  patch_size: *patch_size
  batch_size: 32
  opt_bands: *opt_bands 
  sar_bands: *sar_bands 
  n_opt_images: *n_opt_images 
  n_sar_images: *n_sar_images
  loss_fn: 
    module: torch.nn.CrossEntropyLoss
    ignore_index: 2
    weights: [0.2, 0.8, 0]
  optimizer:
    module: torch.optim.Adam
    params:
      lr: 2.0e-5
  early_stop:
    patience: 10
    min_delta: 1.0e-5
    min_epochs: 0
  max_epochs: 500
  n_classes: *n_classes
prediction_params:
  experiments_paths: *experiments_path
  patch_size: *patch_size
  n_classes: *n_classes
  prediction_prefix: *prediction_prefix
  n_models: *n_models
  batch_size: 32
  prediction_remove_border: 8
  prediction_overlaps: [0.25]
  opt_bands: *opt_bands 
  sar_bands: *sar_bands 
  n_opt_images: *n_opt_images 
  n_sar_images: *n_sar_images


experiments:
  exp_1:
    model: models.resunet.networks.ResUnetOpt
    opt_bands: *opt_bands
    n_opt_images: *n_opt_images 
    n_classes: *n_classes
    resunet_depths: *resunet_depths
  exp_2:
    model: models.resunet.networks.ResUnetSAR
    sar_bands: *sar_bands
    n_sar_images: *n_sar_images 
    n_classes: *n_classes
    resunet_depths: *resunet_depths
