#! /bin/bash
python train.py -d 0 -s 2 -e 7 -i 5
python predict.py -d 0 -s 2 -e 7
python evaluate.py -s 2 -e 7

python train.py -d 0 -s 2 -e 8 -i 5
python predict.py -d 0 -s 2 -e 8
python evaluate.py -s 2 -e 8
