#! /bin/bash
python train.py -e 11 -d 0
python predict.py -e 11 -d 0
python evaluate.py -e 11

python train.py -e 12 -d 0
python predict.py -e 12 -d 0
python evaluate.py -e 12

python train.py -e 13 -d 0
python predict.py -e 13 -d 0
python evaluate.py -e 13

python train.py -e 17 -d 0
python predict.py -e 17 -d 0
python evaluate.py -e 17





