#! /bin/bash
python train.py -d 1 -s 1 -e 53
python predict.py -d 1 -s 1 -e 53
python evaluate.py -s 1 -e 53

python train.py -d 1 -s 1 -e 54
python predict.py -d 1 -s 1 -e 54
python evaluate.py -s 1 -e 54