#! /bin/bash
python predict.py -d 1 -s 2 -e 54
python evaluate.py -s 2 -e 54

python train.py -d 1 -s 2 -e 55
python predict.py -d 1 -s 2 -e 55
python evaluate.py -s 2 -e 55

python train.py -d 1 -s 2 -e 56
python predict.py -d 1 -s 2 -e 56
python evaluate.py -s 2 -e 56