#! /bin/bash
python train.py -d 1 -s 1 -e 68
python predict.py -d 1 -s 1 -e 68
python evaluate.py -s 1 -e 68

python train.py -d 1 -s 1 -e 69
python predict.py -d 1 -s 1 -e 69
python evaluate.py -s 1 -e 69

python train.py -d 1 -s 1 -e 70
python predict.py -d 1 -s 1 -e 70
python evaluate.py -s 1 -e 70

python train.py -d 1 -s 1 -e 71
python predict.py -d 1 -s 1 -e 71
python evaluate.py -s 1 -e 71