python predict.py -e 3
python predict.py -e 4
python predict.py -e 5
python predict.py -e 6
python predict.py -e 7
python predict.py -e 8
python predict.py -e 9
python predict.py -e 10

python evaluate.py -e 1
python evaluate.py -e 2
python evaluate.py -e 3
python evaluate.py -e 4
python evaluate.py -e 5
python evaluate.py -e 6
python evaluate.py -e 7
python evaluate.py -e 8
python evaluate.py -e 9
python evaluate.py -e 10